### ISSUE TITLE
随着3.2更新似乎换salt了

### ISSUE THREAD

**Issue by misaka-20002** [armoe-project/mihoyo-api#2]
现在不管怎么获取都会返回422
我猜测是换salt导致DS出错）

**Comment by RealHeart** [comment]
请提供完整返回Body

**Comment by misaka-20002** [comment]
> 请提供完整返回Body

{"code":422,"msg":""}
换过cookies也是返回这个

**Comment by RealHeart** [comment]
> > 请提供完整返回Body
> 
> {"code":422,"msg":""} 换过cookies也是返回这个


尝试请求 `https://mhy.armoe.cn/` 查看返回结果是否一致.
请求需携带cookie: `ltoken`, `ltuid`, `cookie_token`, `account_id`

我这边测试正常

![image](https://user-images.githubusercontent.com/24838944/200476164-d5d52e12-328d-4eb5-a756-3bdd39cade8b.png)

**Comment by misaka-20002** [comment]
还是不行
![image](https://user-images.githubusercontent.com/91882141/200483357-63d6a883-42f8-4008-9938-03cee7b383a1.png)
还是返回422
cookie是从无痕浏览获取的

**Comment by RealHeart** [comment]
> 还是不行 ![image](https://user-images.githubusercontent.com/91882141/200483357-63d6a883-42f8-4008-9938-03cee7b383a1.png) 还是返回422 cookie是从无痕浏览获取的

测试正常 
![image](https://user-images.githubusercontent.com/24838944/200483686-d620b5a4-fd8c-4bb3-b849-626bd0542eb3.png)

可以尝试更换其他cookie 从结果来看非程序问题，此issue关闭
